### ISSUE TITLE
ansible reporting: fix 'changed' reporting issues

### ISSUE THREAD

**Issue by 5f6b3fb8** [5f6b3fb8/kubernetes#25]
There are several commands throughout the site play that gather information but do not change the system, yet the status is shown as 'changed' in the summary report for the run.

add `changed_when: false` to the task

Also, there are some elements that are being marked 'changed', but it's unclear if the resource is actually changed or if it's just reported that way. In those cases, make sure there is a `when:` conditional on the task to prevent the task from executing. Example: In the glusterfs-server main task file, the thinpool meta task is always changed:

```yaml
- name: create thinpool meta LV
  lvol:
    vg: gfs_vg
    lv: gfs_pool_meta
    size: "{{glusterfs.metadata_size}}"
```
